#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-m   += ektf2k.o
obj-y	+= elan_platform.o
obj-$(CONFIG_TOUCHSCREEN_ELAN)   += Laibao_for_Dell7_V5511_for_20140617.i
obj-$(CONFIG_TOUCHSCREEN_ELAN)   += WTK_for_Dell7_V5508_0617.i 
#obj-y   += ft5416_touch.o 
